components:
  schemas:
    studio.v2.flow:
      properties:
        account_sid:
          maxLength: 34
          minLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          type: string
        commit_message:
          type: string
        date_created:
          format: date-time
          type: string
        date_updated:
          format: date-time
          type: string
        definition:
          type: object
        errors:
          items:
            type: object
          type: array
        friendly_name:
          type: string
        links:
          type: object
        revision:
          type: integer
        sid:
          maxLength: 34
          minLength: 34
          pattern: ^FW[0-9a-fA-F]{32}$
          type: string
        status:
          enum:
          - draft
          - published
          type: string
        url:
          format: uri
          type: string
        valid:
          type: boolean
        warnings:
          items:
            type: object
          type: array
        webhook_url:
          format: uri
          type: string
      type: object
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Studio
  version: 1.0.0
openapi: 3.0.1
paths:
  /v2/Flows:
    description: Studio flows
    get:
      description: Retrieve a list of all Flows.
      parameters:
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  flows:
                    items:
                      $ref: '#/components/schemas/studio.v2.flow'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                type: object
          description: OK
      security:
      - accountSid_authToken: []
      operationId: FlowsList
      x-path-type: list
    post:
      description: Create a Flow.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                CommitMessage:
                  description: Description on change made in the revision.
                  type: string
                Definition:
                  description: JSON representation of flow definition.
                  type: object
                FriendlyName:
                  description: The string that you assigned to describe the Flow.
                  type: string
                Status:
                  description: 'The status of the Flow. Can be: `draft` or `published`.'
                  enum:
                  - draft
                  - published
                  type: string
              required:
              - FriendlyName
              - Status
              - Definition
              type: object
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/studio.v2.flow'
          description: Created
      security:
      - accountSid_authToken: []
      operationId: FlowsCreate
    servers:
    - url: https://studio.twilio.com
    x-default-output-properties: &id008
    - sid
    - friendly_name
    - status
    - revision
  /v2/Flows/{Sid}:
    delete:
      description: Delete a specific Flow.
      parameters:
      - description: The SID of the Flow resource to delete.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FW[0-9a-fA-F]{32}$
          type: string
      responses:
        204:
          description: The resource was deleted successfully.
      security:
      - accountSid_authToken: []
      operationId: FlowsDelete
    description: Studio flows
    get:
      description: Retrieve a specific Flow.
      parameters:
      - description: The SID of the Flow resource to fetch.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FW[0-9a-fA-F]{32}$
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/studio.v2.flow'
          description: OK
      security:
      - accountSid_authToken: []
      operationId: FlowsRead
    post:
      description: Update a Flow.
      parameters:
      - description: The SID of the Flow resource to fetch.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FW[0-9a-fA-F]{32}$
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                CommitMessage:
                  description: Description on change made in the revision.
                  type: string
                Definition:
                  description: JSON representation of flow definition.
                  type: object
                FriendlyName:
                  description: The string that you assigned to describe the Flow.
                  type: string
                Status:
                  description: 'The status of the Flow. Can be: `draft` or `published`.'
                  enum:
                  - draft
                  - published
                  type: string
              required:
              - Status
              type: object
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/studio.v2.flow'
          description: OK
      security:
      - accountSid_authToken: []
      operationId: FlowsUpdate
    servers:
    - url: https://studio.twilio.com
    x-default-output-properties: *id008
    x-path-type: instance
